### ISSUE TITLE
Tests are incomplete?

### ISSUE THREAD

**Issue by therealklanni** [jsdevel/node-tmp-debug#1]
The tests don't appear to actually test anything. Consider [test/tmp-debug.specs.js#L36-L40](https://github.com/jsdevel/node-tmp-debug/blob/master/test/tmp-debug.specs.js#L36-L40):

``` js
    describe('log', function() {
      it('should log', function() {
        tmpDebug.log('asdfasdf');
      });
    });
```

There are no assertions! :fearful:

While it's true that the methods being called are not throwing any errors, how do we know if they're actually doing what they're supposed to do? I can probably safely assume that the tests are just incomplete.

Also, even though istanbul is reporting 100% coverage, not all lines are being hit (I didn't manually check all lines, but at least some aren't). [lib/tmp-debug.js#L92](https://github.com/jsdevel/node-tmp-debug/blob/master/lib/tmp-debug.js#L92) for instance.

And finally, the test process never exits. :cry:

**Comment by jsdevel** [comment]
Thanks for opening this!  Yea, you're completely right.  I was `tail`ing the files produced in `/tmp` while testing, and that's definitely not helpful to others.

I'll read the files in from `/tmp` and assert the logs were written accordingly.
